import { ArtillerieAllies, ArtillerieAxis, CharAllies, CharAxis, SoldatAllies, SoldatAxis, UnitEliteAxis } from "../../army/army"
import { Bunker, Forest, Hills, Mine, RiversCurve, RiversRight, SandBag, Village, Wire } from "../../haxagone/base"
import { Medal } from "../../haxagone/highlight"
import { LakeC, Mountain } from "../../haxagone/terrain"

export const ligne_san_fratello= {
name:"La ligne de san fratello",
terrain:"terrain0",
medalAllies:6,
medalAxe:6,
camp:"Axis",
cardAxis:6,
cardAllies:6,
campMine:"Axis",
hexa:[
   {x:0,y:0,contenu:{case: new Village(),bunker: null,defense: new SandBag(1), unité:new UnitEliteAxis(4),medal:new Medal(),action:null,highlight:null,select:null}}, 
   {x:0,y:1,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:0,y:2,contenu:{case: new Forest(),bunker: null,defense: null, unité:new CharAxis(3,[3,3,3],[1,1,1]),medal:null,action:null,highlight:null,select:null}}, 
   {x:0,y:3,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:0,y:4,contenu:{case: new Hills(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:0,y:5,contenu:{case: new Mountain(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:0,y:6,contenu:{case: new Mountain(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:0,y:7,contenu:{case: new Mountain(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:0,y:8,contenu:{case: new Mountain(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:0,y:9,contenu:{case: new Mountain(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:0,y:10,contenu:{case: new Mountain(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:0,y:11,contenu:{case: new Hills(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:0,y:12,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 

   {x:1,y:0,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:1,y:1,contenu:{case: new Forest(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:1,y:2,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:1,y:3,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:1,y:4,contenu:{case: new Hills(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:1,y:5,contenu:{case: new Hills(),bunker: null,defense: null, unité:new ArtillerieAxis(2,[3,3,2,2,1,1],[2]),medal:null,action:null,highlight:null,select:null}}, 
   {x:1,y:6,contenu:{case: new Hills(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:1,y:7,contenu:{case: new Hills(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:1,y:8,contenu:{case: new Village(),bunker: null,defense: new SandBag(1), unité:new UnitEliteAxis(),medal:new Medal(),action:null,highlight:null,select:null}}, 
   {x:1,y:9,contenu:{case: new Hills(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:1,y:10,contenu:{case: new Hills(),bunker: new Bunker(),defense: null, unité:new SoldatAxis(4,[3,2,1],[1,2]),medal:null,action:null,highlight:null,select:null}}, 
   {x:1,y:11,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:1,y:12,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 

   {x:2,y:0,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:2,y:1,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:2,y:2,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:2,y:3,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:2,y:4,contenu:{case: new Village(),bunker: null,defense: new SandBag(1), unité:new SoldatAxis(4,[3,2,1],[1,2]),medal:null,action:null,highlight:null,select:null}}, 
   {x:2,y:5,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:2,y:6,contenu:{case: new Hills(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:2,y:7,contenu:{case: new Hills(),bunker: new Bunker(),defense: null, unité:new SoldatAxis(4,[3,2,1],[1,2]),medal:null,action:null,highlight:null,select:null}}, 
   {x:2,y:8,contenu:{case: new Hills(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:2,y:9,contenu:{case: new Hills(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:2,y:10,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:2,y:11,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:2,y:12,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 

   {x:3,y:0,contenu:{case: new Village(),bunker: null,defense: new SandBag(1), unité:new SoldatAxis(4,[3,2,1],[1,2]),medal:null,action:null,highlight:null,select:null}}, 
   {x:3,y:1,contenu:{case: null,bunker: new Mine(),defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:3,y:2,contenu:{case: null,bunker: new Mine(),defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:3,y:3,contenu:{case: null,bunker: null,defense: new Wire(), unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:3,y:4,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:3,y:5,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:3,y:6,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:3,y:7,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:3,y:8,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:3,y:9,contenu:{case: null,bunker: null,defense: new Wire(), unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:3,y:10,contenu:{case: null,bunker: new Mine(),defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:3,y:11,contenu:{case: null,bunker: null,defense: new Wire(), unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:3,y:12,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 

   {x:4,y:0,contenu:{case: new LakeC(4),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:4,y:1,contenu:{case: new RiversRight(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:4,y:2,contenu:{case: new RiversRight(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:4,y:3,contenu:{case: new RiversCurve(5),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:4,y:4,contenu:{case: null,bunker: null,defense: new Wire(), unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:4,y:5,contenu:{case: null,bunker: new Mine(),defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:4,y:6,contenu:{case: null,bunker: new Mine(),defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:4,y:7,contenu:{case: null,bunker: new Mine(),defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:4,y:8,contenu:{case: null,bunker: new Mine(),defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:4,y:9,contenu:{case: null,bunker: new Mine(),defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:4,y:10,contenu:{case: new RiversCurve(6),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:4,y:11,contenu:{case: new RiversRight(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:4,y:12,contenu:{case: new RiversRight(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 

   {x:5,y:0,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:5,y:1,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:5,y:2,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:5,y:3,contenu:{case: new RiversCurve(2),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:5,y:4,contenu:{case: new RiversRight(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:5,y:5,contenu:{case: new RiversRight(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:5,y:6,contenu:{case: new RiversRight(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:5,y:7,contenu:{case: new RiversRight(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:5,y:8,contenu:{case: new RiversRight(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:5,y:9,contenu:{case: new RiversCurve(3),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:5,y:10,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:5,y:11,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:5,y:12,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 

   {x:6,y:0,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:6,y:1,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:6,y:2,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:6,y:3,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:6,y:4,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:6,y:5,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:6,y:6,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:6,y:7,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:6,y:8,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:6,y:9,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:6,y:10,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:6,y:11,contenu:{case: new Forest(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:6,y:12,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 

   {x:7,y:0,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:7,y:1,contenu:{case: new Forest(),bunker: null,defense: null, unité:new SoldatAllies(4,[3,2,1],[1,2]),medal:null,action:null,highlight:null,select:null}}, 
   {x:7,y:2,contenu:{case: new Forest(),bunker: null,defense: null, unité:new SoldatAllies(4,[3,2,1],[1,2]),medal:null,action:null,highlight:null,select:null}}, 
   {x:7,y:3,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:7,y:4,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:7,y:5,contenu:{case: new Hills(),bunker: null,defense: null, unité:new SoldatAllies(4,[3,2,1],[1,2]),medal:null,action:null,highlight:null,select:null}}, 
   {x:7,y:6,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:7,y:7,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:7,y:8,contenu:{case: new Forest(),bunker: null,defense: null, unité:new SoldatAllies(4,[3,2,1],[1,2]),medal:null,action:null,highlight:null,select:null}}, 
   {x:7,y:9,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:7,y:10,contenu:{case: new Forest(),bunker: null,defense: null, unité:new SoldatAllies(4,[3,2,1],[1,2]),medal:null,action:null,highlight:null,select:null}}, 
   {x:7,y:11,contenu:{case: null,bunker: null,defense: null, unité:new SoldatAllies(4,[3,2,1],[1,2]),medal:null,action:null,highlight:null,select:null}}, 
   {x:7,y:12,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 

   {x:8,y:0,contenu:{case: new Village(),bunker: null,defense: null, unité:new SoldatAllies(4,[3,2,1],[1,2]),medal:null,action:null,highlight:null,select:null}}, 
   {x:8,y:1,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:8,y:2,contenu:{case: null,bunker: null,defense: null, unité:new CharAllies(3,[3,3,3],[1,1,1]),medal:null,action:null,highlight:null,select:null}}, 
   {x:8,y:3,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:8,y:4,contenu:{case: null,bunker: null,defense: null, unité:new SoldatAllies(4,[3,2,1],[1,2]),medal:null,action:null,highlight:null,select:null}}, 
   {x:8,y:5,contenu:{case: new Hills(),bunker: null,defense: null, unité:new ArtillerieAllies(2,[3,3,2,2,1,1],[2]),medal:null,action:null,highlight:null,select:null}}, 
   {x:8,y:6,contenu:{case: new Hills(),bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:8,y:7,contenu:{case: new Hills(),bunker: null,defense: null, unité:new SoldatAllies(4,[3,2,1],[1,2]),medal:null,action:null,highlight:null,select:null}}, 
   {x:8,y:8,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:8,y:9,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 
   {x:8,y:10,contenu:{case: null,bunker: null,defense: null, unité:new CharAllies(3,[3,3,3],[1,1,1]),medal:null,action:null,highlight:null,select:null}}, 
   {x:8,y:11,contenu:{case: null,bunker: null,defense: null, unité:new ArtillerieAllies(2,[3,3,2,2,1,1],[2]),medal:null,action:null,highlight:null,select:null}}, 
   {x:8,y:12,contenu:{case: null,bunker: null,defense: null, unité:null,medal:null,action:null,highlight:null,select:null}}, 

   ]
}
